"""
Agent State Schema

This defines the data structure that flows through the LangGraph workflow.
Each node can read from and write to this state.
"""

from typing import TypedDict, Annotated
from langgraph.graph import add_messages


class AgentState(TypedDict):
    """
    State that flows through the agent graph.
    
    Attributes:
        question: User's input question
        limit: Number of documents to retrieve
        documents: Retrieved documents from vector search
        answer: Generated answer from LLM
        sources: Source documents with metadata
    """
    
    # Input from user
    question: str
    limit: int  # Number of documents to retrieve
    
    # Retrieved from vector store
    documents: list[dict]
    
    # Generated by LLM
    answer: str
    
    # Sources to return to user
    sources: list[dict]
    
    # Optional: For conversation history (future iteration)
    # messages: Annotated[list, add_messages]
